name: Publish package to pub.dev

on:
  release:
    types: [published]

jobs:

  build:

    runs-on: ubuntu-latest

#    container:
#      image:  google/dart:latest

    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
      - name: Setup credentials
        run: |
          mkdir -p $FLUTTER_HOME/.pub-cache
          cat <<EOF > $FLUTTER_HOME/.pub-cache/credentials.json
          {
            "accessToken":"${{ secrets.PUB_DEV_PUBLISH_ACCESS_TOKEN }}",
            "refreshToken":"${{ secrets.PUB_DEV_PUBLISH_REFRESH_TOKEN }}",
            "tokenEndpoint":"${{ secrets.PUB_DEV_PUBLISH_TOKEN_ENDPOINT }}",
            "scopes": [ "openid", "https://www.googleapis.com/auth/userinfo.email" ],
            "expiration": ${{ secrets.PUB_DEV_PUBLISH_EXPIRATION }}
          }
          EOF
      - name: Install dependencies
        run: flutter pub get
      - name: Document plugin
        run: |
          export FLUTTER_ROOT="$FLUTTER_HOME"
          pub global activate dartdoc
          pub global run dartdoc
      - name: Publish plugin
        run: flutter pub publish --force
